version: "3.8"
services:
  nginx-react:
    container_name: my-docker-app-container
    image: my-docker-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 8080:80